### ISSUE TITLE
install from github on windows

### ISSUE THREAD

**Issue by JanSchulz** [eddelbuettel/drat#10]
More or less just for the reference: using the readme example to install directly from github does not work:

```
> install.packages("drat", repos="http://eddelbuettel.github.io/drat")
Installing package into ‘C:/portabel/Rlibs’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://eddelbuettel.github.io/drat/bin/windows/contrib/3.1

   package ‘drat’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘drat’ is not available (as a binary package for R version 3.1.3)
```

**Comment by eddelbuettel** [comment]
See `help(install.packages)` and please try `type="source"`.

**Comment by JanSchulz** [comment]
Ok, I installed from cran (thanks for the above, that also now works), but now what?

My github page is in `c:\data\external\janschulz.github.io`, my package `*.tar.gz` (and `*.zip`) in `c:\rtools`, my r session starts in `C:/Users/jschulz`.

```
> library(drat)
> addRepo("janschulz")
> 
> drat:::insert("C:\\Rtools\\rzmq_0.7.7.tar.gz")
Error in insertPackage(...) : Directory ~/git/drat not found
FALSE
> drat:::insert("C:\\Rtools\\rzmq_0.7.7.tar.gz", "C:\\data\\external\\JanSchulz.github.io\\drat")
Error in insertPackage(...) : 
  Directory C:\data\external\JanSchulz.github.io\drat/src/contrib not found
FALSE
## Adding src\contrib to that dir...
> drat:::insert("C:\\Rtools\\rzmq_0.7.7.tar.gz", "C:\\data\\external\\JanSchulz.github.io\\drat")
# yay, success
```

Somehow this feels a little manual :-(

**Comment by eddelbuettel** [comment]
I am not sure I understand what you point is.:

-  Attempt one failed because the (default) target directory does not exist on your box, and I give a clear error
- Attempt two failed because you had no `src/contrib`; creating is a possible TODO and I recommend to folks to please just clone drat so that they get one
- Attempt three worked fine.

Next attempts, done as three, will work as well.    

If you need more hand-holding in the code, I will consider pull request but I don;t think I have the time or ability to guess what you may be doing next, so it is unlike I will write those changes.  There is a TODO list in source repo...

So can we close this now?

**Comment by eddelbuettel** [comment]
Also if you want to write some documentation on "surviving drat on Windows" I may consider that too.  We could do a guest blog post as Steven and I did.   But again, as I do not work in Windows, I am unlikely to make Windows better you.   You on the other hand may well be a prime candidate for that :)

**Comment by JanSchulz** [comment]
So, i got it to work:

```
> tools::write_PACKAGES("C:\\data\\external\\JanSchulz.github.io\\drat",
+                verbose=TRUE, subdirs=TRUE,
+                type="win.binary")
Bearbeitete Pakete:
  C:\data\external\JanSchulz.github.io\drat/./bin/windows/contrib/3.1/rzmq_0.7.7.zip
fertig
> tools::write_PACKAGES("C:\\data\\external\\JanSchulz.github.io\\drat\\bin\\windows\\contrib\\3.1",
+                       verbose=TRUE, subdirs=TRUE,
+                       type="win.binary")
Bearbeitete Pakete:
  C:\data\external\JanSchulz.github.io\drat\bin\windows\contrib\3.1/rzmq_0.7.7.zip
fertig
> install.packages("rzmq")
Installing package into ‘C:/portabel/Rlibs’
(as ‘lib’ is unspecified)
trying URL 'http://janschulz.github.io/drat/bin/windows/contrib/3.1/rzmq_0.7.7.zip'
Content type 'application/zip' length 681860 bytes (665 KB)
opened URL
downloaded 665 KB
```

**Comment by eddelbuettel** [comment]
Yes, of course.  I have done this "by hand" for private Windows repos at work too.  It works.

The question is:  will you help implement it?

**Comment by JanSchulz** [comment]
A little more handholding would indeed be nice: From you blog post I more or less got the impression that it does some magic to "put my package on my github page" but now it feels more like i still have to do every step by hand :-(

* if the 'github pages' case is what this is optimized for, then the first invocation should print something along the lines of 'You need to specify where your github pages are checked out"
*  There should be an howto, which walks you true the steps of specifying the default location (=checkout of your github pages), inserting a source package (which magically works without adding dirs), inserting a binary package, tell what to do now (aka `git add drat; git commit -m "add package xyz"; git push` and then tell the user what has to be put on a website so other can now install this package

I can produce a PR for the documentation, but my R code is probably not good enough for implementing more :-( I will have a try at the binary version.

**Comment by eddelbuettel** [comment]
It is hard to do this in all generality.  For the Linux case, I can _maybe_ assume `git2r` and probably `git` (the command-line tool). Most Windows users, apart from some power users, have difficulties setting git up, so I can not assume in the path.  

If you sketch some documentation, I will review it.  For now, this is mostly just you saying "oh well this is difficult on Windows" to which I can only answer "yes, working on Windows is in fact difficult" which is why most folks I am in contact prefer to develop on Linux or OS X.  And so I'll close this.
