### ISSUE TITLE
Importing and using large data R package

### ISSUE THREAD

**Issue by pcalhoun1** [eddelbuettel/drat#124]
The drat R package has been very helpful, so thank you for your work on this!  I have read the drat article in the R Journal and have been following the drat step by step instructions to build my own R package that loads a large data R package on GitHub.  I have almost everything working, but want to better understand the process before submitting my R package to CRAN.  Specifically, I have two questions:

1. If a function in the **hurricaneexposure** R package wanted to utilize the rain.rda dataset from the **hurricaneexposuredata** R package imported from GitHub, would the function need write `hurricaneexposuredata::rain` or could one just write `rain`?  The former case seems strange because we don't usually reference the R package when calling a function but instead put them in the Imports field in the DESCRIPTION file (and NAMESPACE file).  However, in the latter case, I would get the note "no visible binding for global variable: rain" when I run R CMD check.

2. I can install my created data R package from GitHub using the instructions from drat, but I noticed that if I uninstall my data R package, then running R CMD check pkgname will create an error message "Package suggested but not available".  Is there any way to run R CMD check on the R package without having the data R package locally installed (thus checking it's installed from GitHub)?  I added the "zzz.R" file that tries to load the data R package as suggested in your article, but is there any way to test this?  Specifically, when I install the R package from source, e.g., `install.packages("pkgname.tar.gz", repos = NULL, type="source")`, I notice that it's not installing the data R package automatically from GitHub, so wanted to confirm it's working correctly.

Any suggestions or thoughts would be greatly appreciated!

**Comment by eddelbuettel** [comment]
Re 1   That is purely an R question on how to access data in another package. So first things first:  `drat` lets you access an external data package so you can i) check if is installed (it is after all only Suggests) and ii) if so access its parts. I'd have to look up myself if one uses `data(rain, package="hurricaneexposuredata")` or not, and if and how that changes with lazydata: yes or not and all that jazz.  But ... that is basically a usage question that is orthogonal to what `drat` does so ok if we move on?

Re 2:  It's just how cannot be a little bit [insert favourite dichotomous adjective here].  _Either the package is installed_ or otherwise _it is not_.  That is what `R CMD check` tells.  And when it is not nomatter how much you wish it were, it still ain't.

Makes sense?

**Comment by eddelbuettel** [comment]
Closing for lack of follow-up.
