### ISSUE TITLE
Broken link in doc ?

### ISSUE THREAD

**Issue by Trowic** [eddelbuettel/drat#137]
Hi,

Link here <https://github.com/eddelbuettel/drat/blob/master/vignettes/DratForPackageAuthors.md?plain=1#L150> seems to be broken.

It points to <https://eddelbuettel.github.io/vignettes/dratforauthors> instead of <https://eddelbuettel.github.io/drat/vignettes/dratforauthors>.

PS: I **love** your work on R packages !

**Comment by eddelbuettel** [comment]
It's complicated (because I am playing with material-for-mkdocs here).  The line you point at is the 'normal' vignette for example rendered [here on the cloud.r-project.org mirror network](https://cloud.r-project.org/web/packages/drat/vignettes/DratForPackageUsers.html).  And there the link to the 'sibbling' vignette works.

What does not work is the link from https://eddelbuettel.github.io/drat/vignettes/dratforauthors/ to its sibbling vignette.  But that is a different source file (below docs/).  Will fix.

**Comment by Trowic** [comment]
Ah yes i see. Thank you for your quick reply.

Do you use the altdoc package to maintain your mkdoc docs ?
https://cran.r-project.org/package=altdoc

**Comment by eddelbuettel** [comment]
No, I use a (simple) set of local scripts and am still experimenting.  That all started because `pkgdown` is just silly by not recognising `ChangeLog` files and insisting only (top-level) `NEWS.md` exists when `inst/NEWS.Rd` was a standard for decades.  But some people argue that stubbornness^H"being opionated" is a virtue. Ah well.  I also find monocultures boring hence the experiment with the (awesome) material-for-mkdocs.

I fixed the authors vignettes. I likely have the same issue in the user vignette. There likely is a simple (better) fix to set a document root (here: with the missing `/drat/` you noticed).  Maybe another day.

Thanks for the heads-up, and the kind words. It's appreciated!
