### ISSUE TITLE
Drat and type = "both"

### ISSUE THREAD

**Issue by hadley** [eddelbuettel/drat#37]
Currently this fails for me:

```R
install.packages("AnomalyDetection", repos = "http://ghrr.github.io/drat")
# curl: (22) The requested URL returned error: 404 Not Found
# Warning in install.packages :
#   download had nonzero exit status
# Warning in install.packages :
#   cannot open compressed file '/tmp/RtmpEjkcSn/file1132c43359019', probable reason 'No such file or # directory'
# curl: (22) The requested URL returned error: 404 Not Found
# Warning in install.packages :
#   download had nonzero exit status
# Warning in install.packages :
#   cannot open compressed file '/tmp/RtmpEjkcSn/file1132c43359019', probable reason 'No such file or # directory'
# Error in install.packages : cannot open the connection
```

I think the warnings are caused by the libcurl buglet @kevinushey reported - 404s don't get converted into R errors. 

Things are a bit better if I use the older internal method:

```R
> install.packages("AnomalyDetection", repos = "http://ghrr.github.io/drat", method = "internal")
Installing package into ‘/Users/hadley/R’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://ghrr.github.io/drat/bin/macosx/mavericks/contrib/3.2
installing the source package ‘AnomalyDetection’
... and the package installs
```

Although there's still two warnings about 404s.  

I wonder if it would be worthwhile for drat to also generate a dummy binary directory structure so that this would work more cleanly.

**Comment by eddelbuettel** [comment]
This seems to generally work for form Ubuntu with `type="source"` (by default).

**Comment by kevinushey** [comment]
There is currently a bug with R + download method `libcurl` that bites if:

1) You're running CRAN R on a platform where binary packages are delivered (OS X or Windows),
2) You have `options(pkgType = "both")` or `options(pkgType = "binary")`,
3) You have a 'source-only' repository in your `options(repos)`.

R will barf on `install.packages()` with something like:

```
Warning: unable to access index for repository http://ghrr.github.io/drat/bin/macosx/mavericks/contrib/3.2:
  Line starting '<!DOCTYPE html> ...' is malformed!
```

because `libcurl` downloads a 404 page and pretends that it is the PACKAGES file it wanted to access. Prior to R 69197, this error was fatal and halted the whole download process; it's appropriately worked around now.

I'm not sure about @hadley's error -- it seems like maybe that was just an intermittent connection issue? But in @hadley's case it's using `curl` itself, not `libcurl`.

@hadley, what's the output of `options("download.file.method")` and `options("download.file.extra")`?

**Comment by eddelbuettel** [comment]
Closing old and stale issue...

**Comment by eddelbuettel** [comment]
Meant to refer to #31 not #37 in that commit two minutes ago...
