### ISSUE TITLE
automate build step

### ISSUE THREAD

**Issue by cboettig** [eddelbuettel/drat#5]
A common use-case I think would be to add an active project to one's local drat repo, e.g. from the directory of an in-development R package I might run:

```r
insertPackage(devtools::build(), commit=TRUE)
```

a quick push and now folks can install releases of my in-development package without CRAN or `install_github`.

**Comment by eddelbuettel** [comment]
Thanks for forking :)  and trying this.

I do not use devtools, so you will have to explain to me what `devtools::build()` does.  As it stands, and the code is in fact very short, we simple copy an existing `.tar.gz` to the target directory.  That pretty much requires a `.tar.gz`.  Will we get one?

**Comment by cboettig** [comment]
It [more-or-less just calls](https://github.com/hadley/devtools/blob/master/R/build.r) R CMD build to create said `.tar.gz` and returns the path to it, as illustrated in my snippet above.  Since `drat` is automating the other simple steps (e.g. just generating the appropriate PACKAGE and file path, etc), it seems it may as well automate this step too. 

Just an idea.  Of course, maybe it's best left to the user to call `insertPackage(devtools::build(), commit=TRUE)` explicitly.

**Comment by eddelbuettel** [comment]
Thanks for the follow-up.  We could add this as a `\dontrun{}` example but then we'd get a spurious depends on devtools just by showing it.  

Maybe documenting this is best left to a blog post?   It does look like the two work well together.

**Comment by cboettig** [comment]
yup, blog post / docs sound good.

**Comment by eddelbuettel** [comment]
I am very much thinking about using the very promising git2r package for the commit step -- but only as a Suggests: to not force. So if `commit=TRUE` _and_ git2r present, then use it.

We could cook up something similar for devtools.  But wouldn't it have to be build _and_ test and only upload and commit if the test was fine?   At some points I still value manual oversight :)

**Comment by eddelbuettel** [comment]
Your use case should now work (with the GitHub version).  There was a possible snafu with absolute paths not in the local directory but I think we got to that.

**Comment by petermeissner** [comment]
Finally comming around to use drat for my own packages I am enthusiatic. 

But, I very much like the idea of having **one function** only for the whole insertion: **check - build - publish**. Since you (Dirk) do not like adding dependencies I build a wrapper around drat and devtools. If you folks like have a look at it: https://github.com/petermeissner/dratful

Now when building a package in Rstudio or beeing a the package folder at the commandline you can simply do:

    dratful::check_build_publish()

... if you like the defaults. If you do not like the defaults you can add whatever options you like since everything will be passed through to `drat::insertPackage()`, `devtools::check()` and `devtools::build`. 

Btw. `dratful::check_build_publish()` will use temporary directories for building to not clutter your file system, it will archive old versions by default and it will only add the package build if the checks pass without any error or warning.

**Comment by eddelbuettel** [comment]
What's this `devtools` thing you are talking about?   ;-)

**Comment by petermeissner** [comment]
Don't worry, it's a Windows only thing :-)
