### ISSUE TITLE
Using S3 for package storage/hosting?

### ISSUE THREAD

**Issue by mccarthyryanc** [eddelbuettel/drat#83]
It looks like there was a bit of a discussion in this issue, https://github.com/eddelbuettel/drat/issues/52#issuecomment-283388857, about using S3. But I figured it was worth asking in a separate issue.

Is there any current or planned support for inserting packages to S3? The idea being that you turn on static hosting for a bucket and simply point users to that bucket URL for the repo.

**Comment by eddelbuettel** [comment]
🤷‍♂ I don't have access to s3 / don't use s3.  

`drat` works with R and specifically the `install.packages()` and `update.packages()` functions. If those can point to an s3 buckets "like a filesystem" then you already have it.  Ditto if you can put a webserver in front.  

Otherwise you may be on your own...  but we could spec out here what you think it would take.  Maybe someone (you?) will then take a stab at it.

**Comment by mccarthyryanc** [comment]
@eddelbuettel , thanks for the response! I should have added more details. I was thinking from the package developer side, where packages are added to a repo via:
```R
drat::insertPackage( 'package.0.1.tar.gz', "/local/path" )
```
But instead of `/local/path`, using an S3 endpoint, something like `s3://bucketname/prefix/`.

It sounds like your recommendation of mounting S3 like a filesystem (possible through [s3fs](https://github.com/s3fs-fuse/s3fs-fuse)) is probably the only way to make this happen.

**Comment by eddelbuettel** [comment]
Yes, we could add other (optional) hooks and push commands ... but who is going to test them?  CRAN cannot run them, Travis CI cannot run them ...   So maybe this is best pushed to documentation?
